- name: Eliminar Podman y herramientas relacionadas
  raw: |
    dnf remove -y podman podman-docker buildah || true
    rm -rf /var/lib/containers /etc/containers || true

- name: Instalar dnf-plugins-core
  raw: dnf install -y dnf-plugins-core

- name: Añadir repositorio oficial de Docker
  raw: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Instalar Docker CE y Docker Compose Plugin
  raw: dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

- name: Habilitar y arrancar Docker
  raw: systemctl enable --now docker
