version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-nfs
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: midb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.17.4.27,nfsvers=4,rw"
      device: ":/srv/nfs/postgresql"
